name: save_video_social_network
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.7
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  flutter_riverpod: ^2.5.1
  introduction_screen: ^3.1.14
  logger: ^2.4.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n